### ISSUE TITLE
Error in datageneration.py

### ISSUE THREAD

**Issue by a-akram-98** [Ozzyz/carla-data-export#5]
I get this error and can't start the generation the version I'm using is 0.8.2

Traceback (most recent call last):
  File "datageneration.py", line 521, in <module>
    main()
  File "datageneration.py", line 512, in main
    game.execute()
  File "datageneration.py", line 152, in execute
    reset = self._on_loop()
  File "datageneration.py", line 190, in _on_loop
    measurements, sensor_data = self.client.read_data()
  File "/media/aakram98/New Volume/CARLA_0.8.2/PythonClient/carla/client.py", line 128, in read_data
    return pb_message, dict(x for x in self._read_sensor_data())
  File "/media/aakram98/New Volume/CARLA_0.8.2/PythonClient/carla/client.py", line 128, in <genexpr>
    return pb_message, dict(x for x in self._read_sensor_data())
RuntimeError: generator raised StopIteration

**Comment by Ozzyz** [comment]
Hey! Apologies for the late response. Maybe you have solved this issue by now, but this looks to be an issue with your configuration of the simulator, not the datageneration itself.
See [here](https://github.com/carla-simulator/carla/issues/545) for more details :)

**Comment by a-akram-98** [comment]
@Ozzyz The problem was in python version indeed, I've downgraded it to 3.6 and it worked

**Comment by Ozzyz** [comment]
Great! Happy to help : )
